a = int(input("Enter the First Number : "))
b = int(input("Enter the Second Number : "))

print("Output of First number + Second Numbee is : " , a+b)
print("Output of First number - Second Numbee is : " , a-b)
print("Output of First number * Second Numbee is : " , a*b)
print("Output of First number / Second Numbee is : " , a/b)
print("Output of First number % Second Numbee is : " , a%b)
print("Output of First number ^ Second Numbee is : " , a**b)
print(a//b)